### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by sm03854** [nicoeps/Logic#1]
I like your project, however, I had to setup a lot of things in the .sln before i could run.

Could you set the default startup project to be Logic.FrontEnd, instead of Logic.Core, and set the application to a Windows Forms application instead of a class library? This will probably reduce confusion for any other users of your program.

Also, is the program finished? I couldn't really do anything except clear the board. Couldn't even create a gate or switch a light off.

**Comment by nicoeps** [comment]
The program is finished and works as intended. You can add new gates by selecting a type in the left menu and then right clicking the grid and selecting "Add". You can toggle switches by either double clicking them or right clicking them and selecting "Toggle". The program can be run by running "dotnet run" inside the "Logic.Frontend" folder.
